### ISSUE TITLE
Homework 2

### ISSUE THREAD

**Issue by pistriak** [polevden/GeekHub#3]
```
public enum Form {
    Circle, circle, CIRCLE,
    Square, square, SQUARE,
    Rectangle, rectangle, RECTANGLE,
    Triangle, triangle, TRIANGLE
}
```
this enum must contain only CIRCLE, SQUARE, RECTANGLE and TRIANGLE;

Reformat your code in IDE; 

Use Math.PI instead of     `final double pi = 3.1415d;`

**Comment by polevden** [comment]
I correct all mistakes.
